# 机器学习100天 第一天：数据预处理

## 导入需要的库  

Numpy 科学计算库；pandas 方便管理处理数据集的库，并且进行过优化对于大数据的时候使用起来速度萌萌哒

In [2]:
import numpy as np
import pandas as pd

# 导入数据集  
pd.read_csv()[官方链接](http://pandas.pydata.org/pandas-docs/stable/io.html)  
我的一些常用方法  
1. 指定数据类型  
pd.read_csv('extLoginFeature_2.csv',dtype={'log_id':str,'id':str,'device':str,'log_from':str,'ip':str,'city':str,'result':str,'type':str})
2. 不用csv文件中的头部  
read_csv('./data.txt',header=None)

In [3]:
dataset=pd.read_csv('../dataset/Data.csv')
#查看前面的5行数据
dataset.head(5)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
#数据最后5行
dataset.tail(5)

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
#数据的基本描述
dataset.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [8]:
#数据的类型，非空数据
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


# 数据切片  
数据切片[参考,我乱找的网友甲的](https://blog.csdn.net/asher117/article/details/83656584)

In [10]:
#不包含最后一列的所有,并转化为了ndarray这样方便后续的sklearn的处理
x=dataset.iloc[:,:-1].values
print(type(x))
print("x")
print(x)
y=dataset['Purchased'].values
print("y")
print(y)

<class 'numpy.ndarray'>
x
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
y
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# 数据预处理
### 处理丢失数据
继续网上乱找一篇热心网友文章[预处理](https://blog.csdn.net/sinat_33761963/article/details/53433799)  
要弥补缺失值，可以使用均值，中位数，众数等等。sklearn.preprocessing库中的Imputer这个类可以实现,这里采用平均数

In [16]:
from sklearn.preprocessing import Imputer
imputer=Imputer(missing_values='NaN',strategy='mean',axis=0)
#sklearn的通用使用方法，先fit
imputer=imputer.fit(x[:,1:3])
#sklearn通用使用方法，在fit后调用变形金刚:)
x[:,1:3]=imputer.transform(x[:,1:3])
print('------------------')
print('处理完毕x的缺失值')
print('x')
print(x)

------------------
处理完毕x的缺失值
x
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# 编码分类数据 
yes,no 这种是标签值，不是数字值，程序不能处理。所以需要进行编码成数字值。
但对于多分类不能简单的进行数字转换，比如有10个分类，转换为0到9则引入了数字的有序性，模型会把它们当成序列型的连续变量。这时候应该是用独热编码OneHotEncoder来处理

In [18]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelEncoder_x=LabelEncoder()
#又是fit，transform方法
x[:,0]=labelEncoder_x.fit_transform(x[:,0])
oneHotEncoder=OneHotEncoder(categorical_features=[0])
x=oneHotEncoder.fit_transform(x).toarray()
labelEncoder_y=LabelEncoder()
y=labelEncoder_y.fit_transform(y)
print('-------------')
print('x')
print(x)
print('y')
print(y)

-------------
x
[[0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.40000000e+01 7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  3.00000000e+01 5.40000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.50000000e+01 5.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.70000000e+01 6.70000000e+04]]
y
[0 1 0 0 1 1 0 1 0 1]


# 拆分数据集为测试集和训练集

把数据集拆分成两个：一个是用来训练模型的训练集合，另一个是用来验证模型的测试集合。两者比例一般是80:20。我们导入sklearn.model_selection库中的train_test_split()方法。

In [19]:
from sklearn.model_selection import train_test_split
#random_state 随机拆分的时候固定初始随机值
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
print("---------------------")
print("Step 5: Splitting the datasets into training sets and Test sets")
print("x_train")
print(x_train)
print("x_test")
print(x_test)
print("y_train")
print(y_train)
print("y_test")
print(y_test)

---------------------
Step 5: Splitting the datasets into training sets and Test sets
x_train
[[1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.70000000e+01 6.70000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.80000000e+01 6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.40000000e+01 7.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.50000000e+01 5.80000000e+04]]
x_test
[[1.0e+00 0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [1.0e+00 0.0e+00 1.0e+00 0.0e+00 5.0e+01 8.3e+04]]
y_train
[1 1 1 0 1 0 0 1]
y_test
[0

# 特征量化
大部分模型算法使用两点间的欧氏距离表示，但此特征在幅度、单位和范围姿态问题上变化很大。在距离计算中，高幅度的特征比低幅度特征权重更大。可用特征标准化或Z值归一化解决。导入sklearn.preprocessing库的StandardScalar类。

In [20]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
## 注意对train使用的是fit_transform，而在后面的test时候是只使用变形.因为只对train训练匹配，对test就直接变换就是了
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
print("---------------------")
print("Step 6: Feature Scaling")
print("x_train")
print(x_train)
print("x_test")
print(x_test)

---------------------
Step 6: Feature Scaling
x_train
[[ 1.         -1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [-1.          1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [ 1.         -1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [ 1.         -1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [-1.          1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [ 1.         -1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [-1.          1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [-1.          1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
x_test
[[ 1.         -1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [ 1.         -1.          2.64575131 -0.77459667  1.98496442  2.13981082]]
